; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = teensy
board = teensy35
framework = arduino
build_flags =
;	-Ofast ; known to introduce some bugs, Teensy libs are tested at -O2
monitor_speed = 115200
lib_deps = 
	hideakitai/DebugLog@^0.6.6
	pedvide/Teensy_ADC@^9.1.0
    janelia-arduino/Array@^1.2.1
	jchristensen/Timezone@^1.2.4
	mkopa/FixedPointBiquad@^1.0.1

[env:production]
build_flags =
	${env.build_flags}
	-DDEBUGLOG_DISABLE_LOG

[env:debug]
