; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = teensy
board = teensy35
framework = arduino
monitor_speed = 115200
lib_deps = 
	hideakitai/DebugLog@^0.6.6
	pedvide/Teensy_ADC@^9.1.0
    janelia-arduino/Array@^1.2.1
	jchristensen/Timezone@^1.2.4
	mkopa/FixedPointBiquad@^1.0.1
build_flags =
	-DUSE_CHILLER_PUMP_PID=1
	-DUSE_COMPRESSOR_PID=1
	; zero out default 280ms delay in teensy startup (pins_teensy.c). add this back if peripheral
	; chips (e.g. MAX) need it. note this has little/no effect since Serial.begin() waits 750-2000ms for USB
	; initialization.
    ;-DTEENSY_INIT_USB_DELAY_AFTER=0

[env:debug]
build_flags =
	${env.build_flags}
	-DRC_DEBUG=1
	-DLOG_SLOW_LOOPS=0
	-DNTC_DEBUG=0
	-DFLOW_DEBUG=0
	-DANF_SAMPLES_TEST=0
;	-DFLUSH_MS=5000
	-DPREALLOC_MB=4 ; 1MB ~= 10 mins of logs, 18MB ~= 4 hours

[env:production]
build_flags =
	${env.build_flags}
	-DDEBUGLOG_DISABLE_LOG
	-DRC_DEBUG=0
	-DLOG_SLOW_LOOPS=0
;	-DFLUSH_MS=5000
;	-DPREALLOC_MB=4
	-DPREALLOC_MB=25 ; use 23 for 3.7h stint @ 175 bytes/100ms
